//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expedia.CodingExercise.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expedia.CodingExercise.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string lblAtoZ {
            get {
                return ResourceManager.GetString("lblAtoZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        public static string lblClearSorting {
            get {
                return ResourceManager.GetString("lblClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Name.
        /// </summary>
        public static string lblDestinationName {
            get {
                return ResourceManager.GetString("lblDestinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Low.
        /// </summary>
        public static string lblHighToLow {
            get {
                return ResourceManager.GetString("lblHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string lblLengthOfStay {
            get {
                return ResourceManager.GetString("lblLengthOfStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-High.
        /// </summary>
        public static string lblLowToHigh {
            get {
                return ResourceManager.GetString("lblLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Guest Rating.
        /// </summary>
        public static string lblMaxGuestRating {
            get {
                return ResourceManager.GetString("lblMaxGuestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Star Rating.
        /// </summary>
        public static string lblMaxStarRating {
            get {
                return ResourceManager.GetString("lblMaxStarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Total Rate.
        /// </summary>
        public static string lblMaxTotalRate {
            get {
                return ResourceManager.GetString("lblMaxTotalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Trip Start Date.
        /// </summary>
        public static string lblMaxTripStartDate {
            get {
                return ResourceManager.GetString("lblMaxTripStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Guest Rating.
        /// </summary>
        public static string lblMinGuestRating {
            get {
                return ResourceManager.GetString("lblMinGuestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Star Rating.
        /// </summary>
        public static string lblMinStarRating {
            get {
                return ResourceManager.GetString("lblMinStarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Total Rate.
        /// </summary>
        public static string lblMinTotalRate {
            get {
                return ResourceManager.GetString("lblMinTotalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Trip Start Date.
        /// </summary>
        public static string lblMinTripStartDate {
            get {
                return ResourceManager.GetString("lblMinTripStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string lblRating {
            get {
                return ResourceManager.GetString("lblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string lblReviews {
            get {
                return ResourceManager.GetString("lblReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &amp; Sort.
        /// </summary>
        public static string lblSearchAndSort {
            get {
                return ResourceManager.GetString("lblSearchAndSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hotel Location.
        /// </summary>
        public static string lblShowHotelLocation {
            get {
                return ResourceManager.GetString("lblShowHotelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Save.
        /// </summary>
        public static string lblYouSave {
            get {
                return ResourceManager.GetString("lblYouSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A.
        /// </summary>
        public static string lblZtoA {
            get {
                return ResourceManager.GetString("lblZtoA", resourceCulture);
            }
        }
    }
}
